### ISSUE TITLE
why it is too slow to load the map

### ISSUE THREAD

**Issue by Bilibilizm** [RadioactivePotato/Better-GeoFS-NAV-Map#1]

**Comment by krunchiekrunch** [comment]
This doesn't seem to be an issue on my end, the tiles are fetched from Google

**Comment by Bilibilizm** [comment]
Ok thank you maybe i should use VPN&nbsp;

**Comment by krunchiekrunch** [comment]
That's probably a good idea

**Comment by Bilibilizm** [comment]
By the way i have a advice if you can do it.Can you achieve slight wing sway when the airplane is taxiing?

**Comment by krunchiekrunch** [comment]
That is possible but I currently have no plan to create such plugin

**Comment by Bilibilizm** [comment]
> That is possible but I currently have no plan to create such plugin

Ok,Hope you can do it,Thanks
